[book]
authors = ["Thorbjornium"]
language = "en"
multilingual = false
src = "src"


[preprocessor.toc]
command = "mdbook-toc"
renderer = ["html"]

[preprocessor.mermaid]
command = "mdbook-mermaid"

[preprocessor.embedify]
scroll-to-top.enable = true


[preprocessor.emojicodes]

[preprocessor.alerts]

[output.html]
site-url = "https://grejor.iventoyguide.app/"
additional-css = ["theme/sun.css", "theme/nordic.css"]

additional-js = ["mermaid.min.js", "mermaid-init.js"]
default-theme = "sun"
preferred-dark-theme = "nordic"
git-repository-url = "https://github.com/thorbjornium/iventoy-guide"
edit-url-template = "https://github.com/thorbjornium/iventoy-guide/blob/main/{path}"


[output.html.print]
enable = true     # include support for printable output
page-break = true # insert page-break after each chapter

[output.html.fold]
enable = false # whether or not to enable section folding
level = 0      # the depth to start folding
